@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
title UC 1: Lav Topmodul ved at importere JSON Konfigurationsfiler

participant ":CreateModuleCommand" as CMC
participant ":MainViewModel" as MVM
participant ":OpenFileDialog" as OFD
participant ":Module" as M
participant ":SBC" as S
participant ":IOBoard" as I
participant ":ModuleRepository" as MR
participant ":ModuleViewModel" as MV
participant ":SBCRepository" as SR
participant ":SBCViewModel" as SV
participant ":IOBoardRepository" as IR
participant ":IOBoardViewModel" as IV




participant ":MessageBox" as MB


[o-> CMC: Execute(parameter)
activate CMC
    CMC -> MVM ++: CreateModule()
        MVM -> OFD **: Create new OpenFileDialog()
        MVM -> OFD ++: Show()
        return moduleJSON.JSON
        create M
        MVM -> M ++: new Module(company : Company, User : User, moduleJSON : string)
            M -> M ++: FormatJSON(moduleJSON : string)
                create S
                M -> S ++: new SBC(model : string, serialNumber : string)
                return 
                create I
                M -> I ++: new IOBoard(applicationVersion : string, kernelVersion : string, boardModel : string)
                return 
            return 
        return module
        MVM -> MR ++: Create(module)
        return 
       
        create MV
        MVM -> MV ++: new ModuleViewModel(Module)
        return module_VM
        MVM -> MVM: ModuleVMs.Add(module_VM)
        MVM -> MVM: SelectedModule_VM = module_VM


        MVM -> SR++: Create(module.SBC)
        return 
        create SV
        MVM -> SV ++: new SBCViewModel(module.SBC)
        return
        MVM -> MVM: ModuleVMs.Add(module_VM)


        MVM -> IR++: Create(module.IOBoard)
        return 
        create IV
        MVM -> IV ++: new IOBoardViewModel(module.IOBoard)
        return
        MVM -> MVM: ModuleVMs.Add(module_VM)
        
        MVM -> MB ++: Show()
        return 
        
    return
   
    


@enduml