@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
title UC5: Opret ny bruger med initialer og navn


participant ": CreateUserCommand" as CUC
participant ": userViewModel" as uvm
participant ": User" as U
participant ": userRepository" as urepo
participant ": mainViewModel" as mvm





participant ":MessageBox" as MB

[o-> CUC++: Execute(parameter)
    create uvm
    CUC -> uvm ++: new UserViewModel(userRepository)
        create U
        uvm --> U ++: new User(initials, name)
        return user
        uvm -> urepo ++: Create(user)
        
        return 
    return user_VM
    CUC -> mvm ++: UserVMs.Add(user_VM));             
        
    return
    CUC -> MB ++: Show()
    return

@enduml