@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
title UC5: Opret ny bruger med initialer og navn


participant ": CreateUserCommand" as CUC
participant ": mainViewModel" as mvm
participant ": User" as U
participant ": userRepository" as urepo

participant ": userViewModel" as uvm

participant ":MessageBox" as MB

[o-> CUC: Execute(parameter)
    CUC -> mvm ++: CreateNewUser()
        create U
        mvm --> U ++: new User(initials, name)
        return user
        mvm -> urepo ++: Create(user)
        urepo -> urepo : users.Add(user)    
        return 
        
        create uvm
        mvm -> uvm ++: new UserViewModel(user)
        return user_VM
        mvm -> mvm: UserVMs.Add(user_VM)
                
        mvm -> MB ++: Show()
        return
    return

@enduml