@startuml
skinparam style strictuml
skinparam SequenceMessageAlignment center
title UC 6: Hent brugerdata(“login”)

Participant "GetUserCommand" as GUC
participant ":MainViewModel" as MVM

[o-> GUC++: Execute(parameter)
    GUC -> MVM++: GetUser()
        
        MVM -> MVM ++:  user_VMs.FirstOrDefault(u => u.Initials == LoginFeald)
        return SelectedUser_VM
        
        MVM -> MVM : Navigate(ModuleListWindow)
    return
    
@enduml